### ISSUE TITLE
Blank view for Custom Template

### ISSUE THREAD

**Issue by ryansena** [OpenCerts/opencerts-documentation#27]
Hi,

As a total newbie, finally managed to learn hashing/signing....
I'm now doing the viewing of our test certificate using custom template.
When I view it in the dev site (it uses the default template obviously ;) ).
When I view it in my local copy of the site using the custom template, I got blank results, please see attached doc for details.

[Issues 22 Jan.docx](https://github.com/OpenCerts/opencerts-documentation/files/2781936/Issues.22.Jan.docx)

**Comment by rjchow** [comment]
please make a fork of the repo and push your changes to a branch there, that way I can see exactly what issues you're having

**Comment by ryansena** [comment]
I did try forking it... and running this command "yarn lint --fix" after i had done my changes.
And I got the following errors instead :

yarn run v1.13.0
$ eslint . --ext .js --max-warnings 0 --fix

C:\GovTech\OpenCert_Site\01_22\opencerts-website\pages\_app.js
   2:15  error  'Container' is defined but never used           no-unused-vars
   5:8   error  'React' is defined but never used               no-unused-vars
   6:10  error  'Provider' is defined but never used            no-unused-vars
  22:13  error  'Component' is assigned a value but never used  no-unused-vars

C:\GovTech\OpenCert_Site\01_22\opencerts-website\pages\_document.js
  2:20  error  'Head' is defined but never used        no-unused-vars
  2:26  error  'Main' is defined but never used        no-unused-vars
  2:32  error  'NextScript' is defined but never used  no-unused-vars

C:\GovTech\OpenCert_Site\01_22\opencerts-website\pages\faq.js
  2:8  error  'Head' is defined but never used           no-unused-vars
  3:8  error  'NavigationBar' is defined but never used  no-unused-vars
  4:8  error  'FooterBar' is defined but never used      no-unused-vars
  5:8  error  'FaqContent' is defined but never used     no-unused-vars

C:\GovTech\OpenCert_Site\01_22\opencerts-website\pages\index.js
  2:8  error  'Head' is defined but never used               no-unused-vars
  3:8  error  'NavigationBar' is defined but never used      no-unused-vars
  4:8  error  'FooterBar' is defined but never used          no-unused-vars
  5:8  error  'MainPageContainer' is defined but never used  no-unused-vars

C:\GovTech\OpenCert_Site\01_22\opencerts-website\pages\privacy.js
  2:8  error  'Head' is defined but never used            no-unused-vars
  3:8  error  'NavigationBar' is defined but never used   no-unused-vars
  4:8  error  'FooterBar' is defined but never used       no-unused-vars
  5:8  error  'PrivacyContent' is defined but never used  no-unused-vars

C:\GovTech\OpenCert_Site\01_22\opencerts-website\pages\registry.js
  2:8  error  'Head' is defined but never used                   no-unused-vars
  3:8  error  'NavigationBar' is defined but never used          no-unused-vars
  4:8  error  'FooterBar' is defined but never used              no-unused-vars
  5:8  error  'RegistryPageContainer' is defined but never used  no-unused-vars

C:\GovTech\OpenCert_Site\01_22\opencerts-website\pages\viewer.js
  2:8  error  'Head' is defined but never used                 no-unused-vars
  3:8  error  'NavigationBar' is defined but never used        no-unused-vars
  4:8  error  'FooterBar' is defined but never used            no-unused-vars
  5:8  error  'ViewerPageContainer' is defined but never used  no-unused-vars
  6:8  error  'PrintWatermark' is defined but never used       no-unused-vars

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\components\CertificateDropZone\CertificateDropZone.js
  1:8  error  'Dropzone' is defined but never used        no-unused-vars
  4:8  error  'DefaultView' is defined but never used     no-unused-vars
  5:8  error  'VerifyingView' is defined but never used   no-unused-vars
  6:8  error  'UnverifiedView' is defined but never used  no-unused-vars

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\components\CertificateDropZone\CertificateDropZoneContainer.js
   1:8  error  'React' is defined but never used                no-unused-vars
  16:8  error  'CertificateDropZone' is defined but never used  no-unused-vars

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\components\CertificateDropZone\Views\UnverifiedView.js
  2:8  error  'Link' is defined but never used  no-unused-vars

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\components\CertificateSharing\CertificateSharingForm.js
  1:8  error  'React' is defined but never used      no-unused-vars
  3:8  error  'ReCAPTCHA' is defined but never used  no-unused-vars

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\components\CertificateTemplates\addDirToTemplatePath.test.js
  3:1  error  'describe' is not defined  no-undef
  4:3  error  'test' is not defined      no-undef
  5:5  error  'expect' is not defined    no-undef

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\components\CertificateTemplates\Default\index.js
  2:10  error  'MultiCertificateRenderer' is defined but never used  no-unused-vars

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\components\CertificateTemplates\index.js
  5:29  error  Parsing error: Unexpected token import

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\components\CertificateTemplates\legacy.js
  6:3  error  Parsing error: Unexpected token import

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\components\CertificateTemplates\MultiCertificateRenderer.js
  2:10  error  'Tabs' is defined but never used                      no-unused-vars
  2:16  error  'TabList' is defined but never used                   no-unused-vars
  2:25  error  'Tab' is defined but never used                       no-unused-vars
  2:30  error  'TabPanel' is defined but never used                  no-unused-vars
  5:8   error  'InvalidCertificateNotice' is defined but never used  no-unused-vars

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\components\CertificateTemplates\sg\edu\np\index.js
  5:3  error  Parsing error: Unexpected token import

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\components\CertificateTemplates\sg\edu\np\NP-AA2018-BMS(CLT)\index.js
  5:10  error  'MultiCertificateRenderer' is defined but never used  no-unused-vars

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\components\CertificateTemplates\sg\edu\np\NP-AA2018-DPP\index.js
  2:10  error  'MultiCertificateRenderer' is defined but never used  no-unused-vars

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\components\CertificateTemplates\sg\edu\np\NP-AA2018-ECH\index.js
  2:10  error  'MultiCertificateRenderer' is defined but never used  no-unused-vars

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\components\CertificateTemplates\sg\edu\np\NP-AA2018-LDH\index.js
  2:10  error  'MultiCertificateRenderer' is defined but never used  no-unused-vars

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\components\CertificateTemplates\sg\edu\np\NP-AA2018-MAIN\index.js
  5:10  error  'MultiCertificateRenderer' is defined but never used  no-unused-vars

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\components\CertificateTemplates\sg\edu\np\NP-AA2018-OPTION\index.js
  4:10  error  'MultiCertificateRenderer' is defined but never used  no-unused-vars

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\components\CertificateTemplates\sg\edu\np\NP-AA2018-PHARM\index.js
  3:10  error  'MultiCertificateRenderer' is defined but never used  no-unused-vars

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\components\CertificateTemplates\sg\edu\singaporetech\2018-certificate\index.js
  3:10  error  'MultiCertificateRenderer' is defined but never used  no-unused-vars

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\components\CertificateTemplates\sg\edu\singaporetech\index.js
  5:3  error  Parsing error: Unexpected token import

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\components\CertificateTemplates\sg\edu\sp\index.js
  5:3  error  Parsing error: Unexpected token import

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\components\CertificateTemplates\sg\edu\sp\SP-2019-MAIN\index.js
  5:10  error  'MultiCertificateRenderer' is defined but never used  no-unused-vars

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\components\CertificateTemplates\sg\gov\tech\2018-OpenCertsAssociate\index.js
  3:10  error  'MultiCertificateRenderer' is defined but never used  no-unused-vars

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\components\CertificateTemplates\sg\gov\tech\2019-OpenCertsAssociate\index.js
  3:10  error  'MultiCertificateRenderer' is defined but never used  no-unused-vars

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\components\CertificateTemplates\sg\gov\tech\index.js
  4:3  error  Parsing error: Unexpected token import

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\components\CertificateVerifyBlock\CertificateVerifyBlock.js
  2:8  error  'DetailedCertificateVerifyBlock' is defined but never used  no-unused-vars

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\components\CertificateViewer.js
  15:3  error  Parsing error: Unexpected token import

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\components\FAQ\FaqContent.js
  5:7  error  'FaqHeader' is assigned a value but never used  no-unused-vars

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\components\HomePageContent\AboutImages.js
  2:8  error  'React' is defined but never used  no-unused-vars

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\components\HomePageContent\AboutSection.js
   4:7  error  'BenefitsSection' is assigned a value but never used  no-unused-vars
  39:7  error  'HowItWorks' is assigned a value but never used       no-unused-vars

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\components\HomePageContent\DropZoneSection.js
  2:8  error  'CertificateDropzone' is defined but never used  no-unused-vars

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\components\HomePageContent\PartnersSection.js
  3:7  error  'CarouselSection' is assigned a value but never used  no-unused-vars

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\components\Layout\FooterBar.js
  1:8  error  'NetworkSelector' is defined but never used  no-unused-vars

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\components\Layout\Meta.js
  1:8  error  'Head' is defined but never used  no-unused-vars

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\components\Layout\NetworkSelector.js
  1:8  error  'React' is defined but never used  no-unused-vars

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\components\MainPageContainer.js
  1:8  error  'AboutSection' is defined but never used     no-unused-vars
  2:8  error  'DropZoneSection' is defined but never used  no-unused-vars
  3:8  error  'PartnerSection' is defined but never used   no-unused-vars

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\components\Privacy\PrivacyContent.js
  3:7  error  'Header' is assigned a value but never used  no-unused-vars
  9:7  error  'Policy' is assigned a value but never used  no-unused-vars

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\components\ViewerPageContainer.js
   1:8  error  'React' is defined but never used              no-unused-vars
  20:8  error  'CertificateViewer' is defined but never used  no-unused-vars

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\components\ViewerPageImages.js
  2:8  error  'React' is defined but never used  no-unused-vars

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\sagas\certificate.test.js
   73:1  error  'describe' is not defined    no-undef
   74:3  error  'describe' is not defined    no-undef
   76:5  error  'beforeEach' is not defined  no-undef
   79:5  error  'afterEach' is not defined   no-undef
   82:5  error  'it' is not defined          no-undef
   88:7  error  'expect' is not defined      no-undef
   89:7  error  'expect' is not defined      no-undef
   96:7  error  'expect' is not defined      no-undef
  101:7  error  'expect' is not defined      no-undef
  104:5  error  'it' is not defined          no-undef
  110:7  error  'expect' is not defined      no-undef
  111:7  error  'expect' is not defined      no-undef
  118:7  error  'expect' is not defined      no-undef
  124:7  error  'expect' is not defined      no-undef
  127:5  error  'it' is not defined          no-undef
  134:7  error  'expect' is not defined      no-undef
  135:7  error  'expect' is not defined      no-undef
  142:7  error  'expect' is not defined      no-undef
  148:7  error  'expect' is not defined      no-undef
  151:3  error  'describe' is not defined    no-undef
  152:5  error  'it' is not defined          no-undef
  157:7  error  'expect' is not defined      no-undef
  162:7  error  'expect' is not defined      no-undef
  167:7  error  'expect' is not defined      no-undef
  170:5  error  'it' is not defined          no-undef
  175:7  error  'expect' is not defined      no-undef
  180:7  error  'expect' is not defined      no-undef
  185:7  error  'expect' is not defined      no-undef
  188:5  error  'it' is not defined          no-undef
  196:7  error  'expect' is not defined      no-undef
  201:7  error  'expect' is not defined      no-undef
  206:7  error  'expect' is not defined      no-undef
  209:5  error  'it' is not defined          no-undef
  222:7  error  'expect' is not defined      no-undef
  226:7  error  'expect' is not defined      no-undef
  231:7  error  'expect' is not defined      no-undef
  240:7  error  'expect' is not defined      no-undef
  243:5  error  'it' is not defined          no-undef
  252:7  error  'expect' is not defined      no-undef
  259:7  error  'expect' is not defined      no-undef
  264:7  error  'expect' is not defined      no-undef
  267:5  error  'it' is not defined          no-undef
  275:7  error  'expect' is not defined      no-undef
  280:7  error  'expect' is not defined      no-undef
  285:7  error  'expect' is not defined      no-undef
  288:5  error  'it' is not defined          no-undef
  296:7  error  'expect' is not defined      no-undef
  301:7  error  'expect' is not defined      no-undef
  304:7  error  'expect' is not defined      no-undef

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\services\email\email.test.js
   5:1  error  'describe' is not defined  no-undef
  10:3  error  'it' is not defined        no-undef
  15:5  error  'expect' is not defined    no-undef
  32:3  error  'it' is not defined        no-undef
  35:5  error  'expect' is not defined    no-undef
  39:3  error  'it' is not defined        no-undef
  42:5  error  'expect' is not defined    no-undef

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\services\ens\ens.test.js
   3:1  error  'describe' is not defined  no-undef
   4:3  error  'describe' is not defined  no-undef
   5:5  error  'test' is not defined      no-undef
   6:7  error  'expect' is not defined    no-undef
   9:7  error  'expect' is not defined    no-undef
  12:7  error  'expect' is not defined    no-undef
  15:7  error  'expect' is not defined    no-undef
  18:7  error  'expect' is not defined    no-undef

C:\GovTech\OpenCert_Site\01_22\opencerts-website\src\utils\index.test.js
   3:1  error  'describe' is not defined                                              no-undef
   4:3  error  'test' is not defined                                                  no-undef
   5:5  error  'expect' is not defined                                                no-undef
  11:1  error  'describe' is not defined                                              no-undef
  12:3  error  'test' is not defined                                                  no-undef
  13:5  error  'expect' is not defined                                                no-undef
  18:3  error  'test' is not defined                                                  no-undef
  19:5  error  'expect' is not defined                                                no-undef
  20:5  error  'expect' is not defined                                                no-undef
  21:5  error  'expect' is not defined                                                no-undef
  24:3  error  'test' is not defined                                                  no-undef
  25:5  error  'expect' is not defined                                                no-undef
  28:3  error  'test' is not defined                                                  no-undef
  29:5  error  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  29:5  error  'expect' is not defined                                                no-undef

✖ 161 problems (161 errors, 0 warnings)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by rjchow** [comment]
use `git commit --no-verify` and `git push --no-verify` to skip the lint checks so that i can see the commit on your repo

**Comment by ryansena** [comment]
Done, please check:

[sp-branch 21cf6a1] Added SP templates
 8 files changed, 819 insertions(+)
 create mode 100644 src/components/CertificateTemplates/sg/edu/sp/SP-2019-MAIN/certificate.js
 create mode 100644 src/components/CertificateTemplates/sg/edu/sp/SP-2019-MAIN/index.js
 create mode 100644 src/components/CertificateTemplates/sg/edu/sp/common/certificate.js
 create mode 100644 src/components/CertificateTemplates/sg/edu/sp/common/functions.js
 create mode 100644 src/components/CertificateTemplates/sg/edu/sp/common/images.js
 create mode 100644 src/components/CertificateTemplates/sg/edu/sp/common/index.js
 create mode 100644 src/components/CertificateTemplates/sg/edu/sp/common/transcript.js
 create mode 100644 src/components/CertificateTemplates/sg/edu/sp/index.js

**Comment by rjchow** [comment]
I'll have a look

**Comment by rjchow** [comment]
So... somehow all the "s got changed to 's and ;s got removed? I don't know how that happened but anyway I ran `npm run lint:fix` and it was all automatically resolved.

Can you show me the sample certificate to replicate your blank screen with?

**Comment by ryansena** [comment]
As requested.
[1_DIP.zip](https://github.com/OpenCerts/opencerts-documentation/files/2785899/1_DIP.zip)

**Comment by rjchow** [comment]
ok a few issues here, poor documentation on our part -

1) you need to amend the index.js at the edu/ level to include sp's template folder so:

```javascript

import addDirToTemplatePath from "../../addDirToTemplatePath";

import singaporetech from "./singaporetech";
import np from "./np";
import sp from "./sp";

export default addDirToTemplatePath("edu", { ...singaporetech, ...np, ...sp });
```

2) the chunkname inside sp/index.js cannot have spaces in it

3) after fixing both of that you should still get a blank white screen as the template you are using is referencing additional data that isn't in your certificate - I recommend you experiment with a basic barebones template first
